In [36]:
import pandas as pd, numpy as np, matplotlib.pyplot as plt, seaborn as sns

# Imputating Missing Values
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

from sklearn.preprocessing import MinMaxScaler, StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split

program_path = './data/01_제공데이터/2020 빅콘테스트 데이터분석분야-챔피언리그_2019년 실적데이터.xlsx'
submission_path = './data/02_평가데이터/2020 빅콘테스트 데이터분석분야-챔피언리그_2020년 6월 판매실적예측데이터(평가데이터).xlsx'

In [10]:
df_raw = pd.read_excel(program_path, header=1); df_raw.head()

방송일시  노출(분)    마더코드    상품코드            상품명 상품군   판매단가  \
0 2019-01-01 06:00:00   20.0  100346  201072  테이트 남성 셀린니트3종  의류  39900   
1 2019-01-01 06:00:00    NaN  100346  201079  테이트 여성 셀린니트3종  의류  39900   
2 2019-01-01 06:20:00   20.0  100346  201072  테이트 남성 셀린니트3종  의류  39900   
3 2019-01-01 06:20:00    NaN  100346  201079  테이트 여성 셀린니트3종  의류  39900   
4 2019-01-01 06:40:00   20.0  100346  201072  테이트 남성 셀린니트3종  의류  39900   

         취급액  
0  2099000.0  
1  4371000.0  
2  3262000.0  
3  6955000.0  
4  6672000.0

In [11]:
df = df_raw.copy()

# 결측치 처리

## 노출 시간 결측치 처리

In [12]:
df.isnull().sum()

방송일시         0
노출(분)    16784
마더코드         0
상품코드         0
상품명          0
상품군          0
판매단가         0
취급액        937
dtype: int64

In [13]:
df.head()

방송일시  노출(분)    마더코드    상품코드            상품명 상품군   판매단가  \
0 2019-01-01 06:00:00   20.0  100346  201072  테이트 남성 셀린니트3종  의류  39900   
1 2019-01-01 06:00:00    NaN  100346  201079  테이트 여성 셀린니트3종  의류  39900   
2 2019-01-01 06:20:00   20.0  100346  201072  테이트 남성 셀린니트3종  의류  39900   
3 2019-01-01 06:20:00    NaN  100346  201079  테이트 여성 셀린니트3종  의류  39900   
4 2019-01-01 06:40:00   20.0  100346  201072  테이트 남성 셀린니트3종  의류  39900   

         취급액  
0  2099000.0  
1  4371000.0  
2  3262000.0  
3  6955000.0  
4  6672000.0

In [24]:
df.loc[df['노출(분)'].isnull()]

방송일시  노출(분)    마더코드    상품코드                  상품명 상품군  \
1     2019-01-01 06:00:00    NaN  100346  201079        테이트 여성 셀린니트3종  의류   
3     2019-01-01 06:20:00    NaN  100346  201079        테이트 여성 셀린니트3종  의류   
5     2019-01-01 06:40:00    NaN  100346  201079        테이트 여성 셀린니트3종  의류   
26    2019-01-01 14:00:00    NaN  100377  201226  그렉노먼 여성 구스다운 롱 벤치코트  의류   
28    2019-01-01 14:30:00    NaN  100377  201226  그렉노먼 여성 구스다운 롱 벤치코트  의류   
...                   ...    ...     ...     ...                  ...  ..   
38298 2019-12-31 23:40:00    NaN  100448  201384        무이자쿠첸압력밥솥 6인용  주방   
38299 2019-12-31 23:40:00    NaN  100448  201391        일시불쿠첸압력밥솥 6인용  주방   
38301 2020-01-01 00:00:00    NaN  100448  201390       일시불쿠첸압력밥솥 10인용  주방   
38302 2020-01-01 00:00:00    NaN  100448  201384        무이자쿠첸압력밥솥 6인용  주방   
38303 2020-01-01 00:00:00    NaN  100448  201391        일시불쿠첸압력밥솥 6인용  주방   

         판매단가          취급액  
1       39900    4371000.0  
3       39900    6955000.0  
5       39900    9337000.0  
26     119000   20841000.0  
28     119000   47294000.0  
...       ...          ...  
38298  158000    2328000.0  
38299  148000   10157000.0  
38301  168000  104392000.0  
38302  158000   13765000.0  
38303  148000   46608000.0  

[16784 rows x 8 columns]

In [57]:
df['year'] = df['방송일시'].dt.year
df['month'] = df['방송일시'].dt.month
df['day'] = df['방송일시'].dt.day
df['hour'] = df['방송일시'].dt.hour
df['minute'] = df['방송일시'].dt.minute

In [58]:
df.head()

방송일시  노출(분)    마더코드    상품코드            상품명 상품군   판매단가  \
0 2019-01-01 06:00:00   20.0  100346  201072  테이트 남성 셀린니트3종  의류  39900   
1 2019-01-01 06:00:00    NaN  100346  201079  테이트 여성 셀린니트3종  의류  39900   
2 2019-01-01 06:20:00   20.0  100346  201072  테이트 남성 셀린니트3종  의류  39900   
3 2019-01-01 06:20:00    NaN  100346  201079  테이트 여성 셀린니트3종  의류  39900   
4 2019-01-01 06:40:00   20.0  100346  201072  테이트 남성 셀린니트3종  의류  39900   

         취급액  year  month  day  hour  minute  
0  2099000.0  2019      1    1     6       0  
1  4371000.0  2019      1    1     6       0  
2  3262000.0  2019      1    1     6      20  
3  6955000.0  2019      1    1     6      20  
4  6672000.0  2019      1    1     6      40

- 마더 코드가 같은 경우에는 노출 시간이 동일한 것으로 파악된다.

In [26]:
df[df['마더코드']==100448]['노출(분)'].unique()

array([20.        ,         nan, 12.13333333])

- 확인 결과 마더코드가 같다고 노출시간이 동일하는 않은 것을 알 수 있다.

In [33]:
df[(df['마더코드']==100448)]

방송일시  노출(분)    마더코드    상품코드                        상품명  \
79    2019-01-02 10:00:00   20.0  100448  202098  일시불 쿠첸 풀스텐 압력밥솥 10인용 (A1)   
80    2019-01-02 10:00:00    NaN  100448  202093   무이자 쿠첸 풀스텐 압력밥솥 10인용(A1)   
81    2019-01-02 10:00:00    NaN  100448  202100    일시불 쿠첸 풀스텐 압력밥솥 6인용(A1)   
82    2019-01-02 10:00:00    NaN  100448  202095    무이자 쿠첸 풀스텐 압력밥솥 6인용(A1)   
83    2019-01-02 10:20:00   20.0  100448  202098  일시불 쿠첸 풀스텐 압력밥솥 10인용 (A1)   
...                   ...    ...     ...     ...                        ...   
38299 2019-12-31 23:40:00    NaN  100448  201391              일시불쿠첸압력밥솥 6인용   
38300 2020-01-01 00:00:00   20.0  100448  201383             무이자쿠첸압력밥솥 10인용   
38301 2020-01-01 00:00:00    NaN  100448  201390             일시불쿠첸압력밥솥 10인용   
38302 2020-01-01 00:00:00    NaN  100448  201384              무이자쿠첸압력밥솥 6인용   
38303 2020-01-01 00:00:00    NaN  100448  201391              일시불쿠첸압력밥솥 6인용   

      상품군    판매단가          취급액  
79     주방  158000    7239000.0  
80     주방  168000    8951000.0  
81     주방  148000    2118000.0  
82     주방  158000    2262000.0  
83     주방  158000   27223000.0  
...    ..     ...          ...  
38299  주방  148000   10157000.0  
38300  주방  178000   50929000.0  
38301  주방  168000  104392000.0  
38302  주방  158000   13765000.0  
38303  주방  148000   46608000.0  

[1308 rows x 8 columns]

In [62]:
df.columns

Index(['방송일시', '노출(분)', '마더코드', '상품코드', '상품명', '상품군', '판매단가', '취급액', 'year',
       'month', 'day', 'hour', 'minute'],
      dtype='object')

In [63]:
tmp = df[['노출(분)', '마더코드', '상품코드', 'year', 'month', 'day', 'hour', 'minute']]

In [64]:
tmp

노출(분)    마더코드    상품코드  year  month  day  hour  minute
0      20.000000  100346  201072  2019      1    1     6       0
1            NaN  100346  201079  2019      1    1     6       0
2      20.000000  100346  201072  2019      1    1     6      20
3            NaN  100346  201079  2019      1    1     6      20
4      20.000000  100346  201072  2019      1    1     6      40
...          ...     ...     ...   ...    ...  ...   ...     ...
38304  20.000000  100073  200196  2020      1    1     0      20
38305  20.000000  100073  200196  2020      1    1     0      40
38306  20.000000  100073  200196  2020      1    1     1       0
38307  20.000000  100490  201478  2020      1    1     1      20
38308  17.166667  100490  201478  2020      1    1     1      40

[38309 rows x 8 columns]

In [65]:
train_set, test_set = train_test_split(tmp, test_size=0.3, shuffle=False)

In [66]:
train_set

노출(분)    마더코드    상품코드  year  month  day  hour  minute
0       20.0  100346  201072  2019      1    1     6       0
1        NaN  100346  201079  2019      1    1     6       0
2       20.0  100346  201072  2019      1    1     6      20
3        NaN  100346  201079  2019      1    1     6      20
4       20.0  100346  201072  2019      1    1     6      40
...      ...     ...     ...   ...    ...  ...   ...     ...
26811    NaN  100205  200737  2019      9   10    22      40
26812    NaN  100205  200739  2019      9   10    22      40
26813   20.0  100150  200533  2019      9   10    23       0
26814    NaN  100150  200465  2019      9   10    23       0
26815   20.0  100150  200533  2019      9   10    23      20

[26816 rows x 8 columns]

In [67]:
np.array(train_set)

array([[2.00000e+01, 1.00346e+05, 2.01072e+05, ..., 1.00000e+00,
        6.00000e+00, 0.00000e+00],
       [        nan, 1.00346e+05, 2.01079e+05, ..., 1.00000e+00,
        6.00000e+00, 0.00000e+00],
       [2.00000e+01, 1.00346e+05, 2.01072e+05, ..., 1.00000e+00,
        6.00000e+00, 2.00000e+01],
       ...,
       [2.00000e+01, 1.00150e+05, 2.00533e+05, ..., 1.00000e+01,
        2.30000e+01, 0.00000e+00],
       [        nan, 1.00150e+05, 2.00465e+05, ..., 1.00000e+01,
        2.30000e+01, 0.00000e+00],
       [2.00000e+01, 1.00150e+05, 2.00533e+05, ..., 1.00000e+01,
        2.30000e+01, 2.00000e+01]])

In [73]:
imp = IterativeImputer(max_iter=10, random_state=0)
imp.fit(tmp)

# the model learns that the second feature is double the first
res = np.round(imp.transform(tmp[tmp['노출(분)'].isnull()]))
res_1 = pd.DataFrame(res)
res_1[0].unique()

array([21., 20., 22., 19.])